### ISSUE TITLE
Can't reproduce the reported MSRVTT(zero-shot) results with the released model weights

### ISSUE THREAD

**Issue by jiyt17** [TencentARC/MCQ#11]
Hello, thank you for the code of MCQ! We utilize the released weights and follow the data settings, trying to reproduce MSRVTT ZS results. But our result(R@1) is about four points lower than the reported result in the paper. Is there any place we need to pay attention to? Thank you.

**Comment by geyuying** [comment]
The above error happens because of different library versions.  The installation below can solve the problem.

```
conda create -n MCQ python=3.8
conda activate MCQ
pip install torch==1.7.1+cu110 torchvision==0.8.2+cu110 torchaudio==0.7.2 -f https://download.pytorch.org/whl/torch_stable.html
pip install -r requirements.txt
```

**Comment by jiyt17** [comment]
ok thank you！

**Comment by shufangxun** [comment]
> ok thank you！

Hello, do you reproduce the zero-shot result?
